#!/usr/bin/env python3
"""Regenerate every figure in docs/ from a real run of the algorithm.

Run from the repository root:  python docs/figs/regenerate.py

Nothing here is drawn by hand.  The worked examples re-run the search and read
the boxes, centres and maximisers out of it; the result charts carry the
numbers the README and the note quote.  No third-party dependency: the figures
are LaTeX `picture` primitives, emitted by docs/figs/canvas.py.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, ROOT)

from canvas import Axes, Canvas                                   # noqa: E402
from lfp_efficient import (FractionalObjective, LE, MOILP, Model)  # noqa: E402
from tracer import (enumerate_points, trace, trace_after_seeding,  # noqa: E402
                    trace_seeding)                                # noqa: E402

OUT = HERE
BOX, CUT, EFF, INC, PT = ("blue!60!black", "red!65!black",
                          "green!45!black", "orange!85!black", "black!45")


def write(name, canvas):
    with open(os.path.join(OUT, name + ".tex"), "w") as fh:
        fh.write("% generated by docs/figs/regenerate.py -- do not edit by hand\n")
        fh.write(canvas.tex() + "\n")


# --------------------------------------------------------------------------
# the two instances, and what the search does on them
# --------------------------------------------------------------------------
def instance_a():
    model = (Model(2).add([-2, 1], LE, 0).add([6, 1], LE, 21).add([-2, 4], LE, 6))
    return (MOILP(model, [[1, -2], [-1, 4]]),
            FractionalObjective([1, 1], [5, 1], -1, -1), [6, 12])


def instance_b():
    model = (Model(3).add([1, 0, 0], LE, 3).add([0, 1, 0], LE, 3)
             .add([0, 0, 1], LE, 3).add([1, 1, 2], LE, 5).add([2, 3, 1], LE, 6))
    return (MOILP(model, [[4, -1, 1], [0, 2, 2]]),
            FractionalObjective([-2, 4, -3], [1, 2, 1], 1, 1), [3, 3, 3])


def criterion_figure(problem, feasible, efficient, step, xlim, ylim,
                     xticks, yticks, children=True):
    a = Axes(205, 150, xlim, ylim, pad=30)
    a.axes("$Z_1$", "$Z_2$", xticks, yticks)
    lo_b, hi_b = step["box"]
    # The region the cut deletes: { Z <= Z(centre) } intersected with the box.
    # Shading that rather than the box itself is what makes a split legible --
    # the first version filled the whole box and the split vanished into it.
    if children and step.get("centre"):
        z = problem.Z(step["centre"])
        cut_hi = [min(z[k], hi_b[k]) if hi_b[k] is not None else z[k]
                  for k in range(problem.p)]
        a.box(lo_b, cut_hi, "red!35", "red!11")
    a.box(lo_b, hi_b, BOX, None, width=1.1)
    if children:
        for lo, hi in (step.get("children") or []):
            a.box(lo, hi, CUT, None, dash=2)
    eff = {tuple(x) for x in efficient}
    for x in feasible:
        z = problem.Z(x)
        X, Y = a.X(z[0]), a.Y(z[1])
        if not (a.pad - 2 <= X <= a.pad + a.iw + 2
                and a.pad - 2 <= Y <= a.pad + a.ih + 2):
            continue
        if tuple(x) in eff:
            a.dot(X, Y, 2.2, EFF)
        else:
            a.ring(X, Y, 2.2, PT)
    if step.get("x"):
        z = problem.Z(step["x"])
        a.ring(a.X(z[0]), a.Y(z[1]), 4.2, CUT, 1.0)
    if step.get("centre"):
        z = problem.Z(step["centre"])
        a.ring(a.X(z[0]), a.Y(z[1]), 5.8, INC, 1.0)
    return a


def decision_2d(problem, feasible, efficient, opt):
    a = Axes(175, 140, (0, 4), (0, 4), pad=30)
    a.axes("$x_1$", "$x_2$", [0, 1, 2, 3, 4], [0, 1, 2, 3, 4])
    eff = {tuple(x) for x in efficient}
    for x in feasible:
        X, Y = a.X(x[0]), a.Y(x[1])
        if tuple(x) in eff:
            a.dot(X, Y, 2.4, EFF)
        else:
            a.ring(X, Y, 2.4, PT)
    if opt:
        a.ring(a.X(opt[0]), a.Y(opt[1]), 5.2, INC, 1.0)
    return a


def decision_3d(problem, feasible, efficient, opt, ub=3):
    step, w = 12, 62
    a = Canvas(3 * w + 20, 96)
    eff = {tuple(x) for x in efficient}
    for li, level in enumerate((0, 1, 2)):
        ox, oy = li * (w + 6) + 22, 24
        a.seg(ox - 4, oy, ox + ub * step + 7, oy, "black!55", 0.6)
        a.seg(ox, oy - 4, ox, oy + ub * step + 7, "black!55", 0.6)
        for v in range(ub + 1):
            a.text(ox + v * step, oy - 8, f"${v}$", "c")
            a.text(ox - 5, oy + v * step, f"${v}$", "r")
        for x in feasible:
            if int(x[2]) != level:
                continue
            X, Y = ox + float(x[0]) * step, oy + float(x[1]) * step
            if tuple(x) in eff:
                a.dot(X, Y, 2.4, EFF)
            else:
                a.ring(X, Y, 2.4, PT)
            if opt and tuple(x) == tuple(opt):
                a.ring(X, Y, 5.0, INC, 1.0)
        a.text(ox + ub * step / 2, oy + ub * step + 15, f"$x_3={level}$", "c",
               "\\footnotesize")
    return a


# --------------------------------------------------------------------------
# the hybrid, step by step
# --------------------------------------------------------------------------
def hybrid_figure(problem, feasible, efficient, step, xlim, ylim,
                  xticks, yticks, walk=None):
    """One seeding step: the box list after this seed is placed.

    Green fills are efficient points, grey outlines dominated ones.  The orange
    ring is the seed just placed; the red shading is the region its split
    removes; the blue dashed rectangles are the boxes now open.  When *walk* is
    given, every archive member is ringed instead -- that is the figure for the
    heuristic phase, before any box exists.
    """
    a = Axes(205, 150, xlim, ylim, pad=30)
    a.axes("$Z_1$", "$Z_2$", xticks, yticks)
    if step is not None:
        lo_b, hi_b = step["target"]
        z = step["z"]
        cut_hi = [min(z[k], hi_b[k]) if hi_b[k] is not None else z[k]
                  for k in range(problem.p)]
        a.box(lo_b, cut_hi, "red!35", "red!11")
        for lo, hi in step["boxes"]:
            a.box(lo, hi, CUT, None, dash=2)
    eff = {tuple(x) for x in efficient}
    for x in feasible:
        z = problem.Z(x)
        X, Y = a.X(z[0]), a.Y(z[1])
        if not (a.pad - 2 <= X <= a.pad + a.iw + 2
                and a.pad - 2 <= Y <= a.pad + a.ih + 2):
            continue
        a.dot(X, Y, 2.2, EFF) if tuple(x) in eff else a.ring(X, Y, 2.2, PT)
    for point in (walk or []):
        z = problem.Z(point)
        a.ring(a.X(z[0]), a.Y(z[1]), 4.6, INC, 1.0)
    if step is not None:
        z = step["z"]
        a.ring(a.X(z[0]), a.Y(z[1]), 5.8, INC, 1.0)
    return a


def empty_boxes_figure(problem, feasible, efficient, boxes, xlim, ylim,
                       xticks, yticks):
    """What the exact phase is left with: boxes that all turn out empty."""
    a = Axes(205, 150, xlim, ylim, pad=30)
    a.axes("$Z_1$", "$Z_2$", xticks, yticks)
    for lo, hi in boxes:
        a.box(lo, hi, CUT, None, dash=2)
    eff = {tuple(x) for x in efficient}
    for x in feasible:
        z = problem.Z(x)
        X, Y = a.X(z[0]), a.Y(z[1])
        if not (a.pad - 2 <= X <= a.pad + a.iw + 2
                and a.pad - 2 <= Y <= a.pad + a.ih + 2):
            continue
        a.dot(X, Y, 2.2, EFF) if tuple(x) in eff else a.ring(X, Y, 2.2, PT)
    return a


def process_diagram():
    """The three phases and what crosses between them."""
    a = Canvas(430, 168)
    boxes = [
        (8,   104, 118, 44, "blue!55!black",  "1. Pareto local search",
         ["archive of candidates", "no proof, $0.011$\\,s"]),
        (156, 104, 118, 44, "orange!80!black", "2. verify \\& order",
         ["one efficiency test each", "sort by probe direction"]),
        (304, 104, 118, 44, "green!45!black", "3. pre-split",
         ["place each seed,", "no program at all"]),
        (8,    14, 118, 44, "black!55",       "6. slices",
         ["solve $\\Z(x)=v$,", "eliminate $r$ variables"]),
        (156,  14, 118, 44, "black!55",       "5. exact enumeration",
         ["probe what is left,", "prove the front complete"]),
        (304,  14, 118, 44, "black!55",       "4. box list",
         ["seeded region,", "the model never grows"]),
    ]
    for x, y, w, h, color, title, lines in boxes:
        a.frame(x, y, w, h, color, 1.0)
        a.text(x + w / 2, y + h - 11, title, "c", "\\footnotesize\\bfseries")
        for i, line in enumerate(lines):
            a.text(x + w / 2, y + h - 24 - 11 * i, line, "c")
    for x1, x2, y in ((126, 156, 126), (274, 304, 126),
                      (304, 274, 36), (156, 126, 36)):
        a.seg(x1, y, x2, y, "black!65", 0.9)
        d = 3 if x2 > x1 else -3
        a.seg(x2, y, x2 - d, y + 3, "black!65", 0.9)
        a.seg(x2, y, x2 - d, y - 3, "black!65", 0.9)
    a.seg(363, 104, 363, 58, "black!65", 0.9)
    a.seg(363, 58, 360, 62, "black!65", 0.9)
    a.seg(363, 58, 366, 62, "black!65", 0.9)
    a.text(214, 92, "verified efficient points, in probe order", "c")
    a.text(371, 80, "boxes", "l")
    a.text(289, 44, "$F$", "c")
    a.text(141, 44, "$E(P_D)$", "c")
    return a


# --------------------------------------------------------------------------
# result charts
# --------------------------------------------------------------------------
def bars(rows, ylabel, width=250, height=130, colors=None, scale=None):
    """Grouped bars: rows = [(label, [v1, v2, ...]), ...]."""
    a = Canvas(width, height)
    n, g = len(rows), len(rows[0][1])
    top = scale or max(max(vs) for _, vs in rows)
    left, base, usable = 34, 26, width - 46
    slot = usable / n
    bw = slot / (g + 0.8)
    colors = colors or ["blue!55!black", "orange!80!black", "green!45!black"]
    a.seg(left - 4, base, left + usable, base, "black!55", 0.6)
    a.seg(left, base - 4, left, base + height - 44, "black!55", 0.6)
    for frac in (0.0, 0.5, 1.0):
        y = base + frac * (height - 50)
        a.seg(left - 3, y, left, y, "black!55", 0.6)
        a.text(left - 5, y, f"${fmt_num(top * frac)}$", "r")
    plot_h = height - 50
    for i, (label, vs) in enumerate(rows):
        for j, v in enumerate(vs):
            x = left + i * slot + 5 + j * bw
            h = (v / top) * plot_h if top else 0
            # `picture` does not clip: an unclamped bar overprints whatever sits
            # above the figure, which is exactly what the first version did.
            clipped = h > plot_h
            a.fill(x, base, bw * 0.86, max(min(h, plot_h), 0.6),
                   colors[j % len(colors)])
            if clipped:
                for k in range(3):
                    a.seg(x, plot_h + base + 2 + 2.4 * k,
                          x + bw * 0.86, plot_h + base + 2 + 2.4 * k,
                          colors[j % len(colors)], 0.8, dash=1)
        a.text(left + i * slot + slot / 2, base - 9, label, "c")
    a.text(left - 2, base + height - 38, ylabel, "r", "\\footnotesize")
    return a


def fmt_num(v):
    if v >= 1000:
        return f"{v:.0f}"
    if v >= 10:
        return f"{v:.0f}"
    return f"{v:.1f}".rstrip("0").rstrip(".")


def legend(items, width=250):
    a = Canvas(width, 16)
    x = 2
    for label, color in items:
        a.fill(x, 4, 8, 7, color)
        a.text(x + 11, 7, label, "l")
        x += 12 + 5.4 * len(label)
    return a


def main():
    # ---- example A: n = 2, p = 2 (the paper's instance) -------------------
    problem, phi, bounds = instance_a()
    sol, steps = trace(problem, phi)
    feasible, efficient = enumerate_points(problem, bounds)
    write("a-decision", decision_2d(problem, feasible, efficient, sol.x))
    for i, step in enumerate(steps, 1):
        write(f"a-step{i}", criterion_figure(problem, feasible, efficient, step,
                                             (-4, 4), (-4, 10), [-3, 0, 3],
                                             [-3, 0, 3, 6, 9]))

    # ---- example B: n = 3, p = 2 -----------------------------------------
    problem, phi, bounds = instance_b()
    sol, steps = trace(problem, phi)
    feasible, efficient = enumerate_points(problem, bounds)
    write("b-decision", decision_3d(problem, feasible, efficient, sol.x))
    for i, step in enumerate(steps, 1):
        write(f"b-step{i}", criterion_figure(problem, feasible, efficient, step,
                                             (-3, 14), (-1, 8), [0, 4, 8, 12],
                                             [0, 2, 4, 6]))

    # ---- results ----------------------------------------------------------
    write("r-margin", bars(
        [("$p=2$", [0.61, 0.35]), ("$p=3$", [1.02, 0.34]), ("$p=4$", [4.21, 0.61]),
         ("$p=5$", [112.77, 1.09]), ("$p=6$", [26.15, 1.08])],
        "seconds (log-free, clipped)", scale=30))
    write("r-margin-legend", legend([("decision space", "blue!55!black"),
                                     ("criterion space", "orange!80!black")]))
    write("r-improve", bars(
        [("early exit", [733, 549]), ("Ecker", [1466, 1341]),
         ("warm start", [18193, 16169]), ("remembered", [16169, 14602])],
        "before / after", scale=18193))
    write("r-improve-legend", legend([("before", "blue!55!black"),
                                      ("after", "orange!80!black")]))
    write("r-seed", bars(
        [("none", [9.64]), ("Pareto", [7.97]), ("Tcheby.", [13.50])],
        "seconds", colors=["blue!55!black"], scale=14))
    write("r-reach", bars(
        [("reached", [66, 112]), ("unsupported", [0, 29])],
        "of 175 / of 54", scale=175))
    write("r-reach-legend", legend([("weighted sum", "blue!55!black"),
                                    ("Tchebychev", "orange!80!black")]))
    # The probe's direction: cuts are unchanged, the branch & bound is not.
    write("r-probe-nodes", bars(
        [("$n=4$", [658, 1397]), ("$n=5$", [372, 2105])],
        "b\\&b nodes", scale=2105))
    write("r-probe-cuts", bars(
        [("$n=4$", [9, 9]), ("$n=5$", [9, 9])],
        "cuts", scale=10))
    write("r-probe-legend", legend([("maximise a direction", "blue!55!black"),
                                    ("zero objective", "orange!80!black")]))
    # The complete efficient set against the front alone: what is recovered
    # grows as 5^f while the extra time stays under one doubling.
    write("r-complete-gain", bars(
        [("$f=0$", [1]), ("$f=1$", [5]), ("$f=2$", [25]), ("$f=3$", [125])],
        "$|E|/|$front$|$", colors=["green!45!black"], scale=125))
    write("r-complete-cost", bars(
        [("$f=0$", [24, 10]), ("$f=1$", [27, 13]),
         ("$f=2$", [42, 24]), ("$f=3$", [90, 68])],
        "extra time \\%", scale=100))
    write("r-complete-legend", legend([("small front (7)", "blue!55!black"),
                                       ("larger front (13)", "orange!80!black")]))
    # the campaign: 30 instances per p, medians of per-instance ratios
    write("r-campaign-margin", bars(
        [("$p=2$", [1.52]), ("$p=3$", [2.69]), ("$p=4$", [4.99]),
         ("$p=5$", [7.93]), ("$p=6$", [14.57])],
        "median ratio", colors=["blue!55!black"], scale=16))
    write("r-campaign-work", bars(
        [("$p=2$", [1.72, 1.28]), ("$p=3$", [1.40, 1.79]),
         ("$p=4$", [1.19, 2.68]), ("$p=5$", [1.17, 3.16]),
         ("$p=6$", [1.02, 5.37])],
        "ratio", scale=5.5))
    write("r-campaign-work-legend", legend([
        ("sub-programs", "blue!55!black"), ("b\\&b nodes", "orange!80!black")]))
    write("r-campaign-front", bars(
        [("$|F|\\,1$--$4$", [2.7]), ("$|F|\\,5$--$12$", [7.5]),
         ("$|F|\\,13+$", [31.4])],
        "median ratio", colors=["green!45!black"], scale=32))
    # the hybrid that pays, and the order it needed
    write("r-hybrid", bars(
        [("front", [1.33]), ("$E(P_D)$", [1.31]), ("probes", [0.72])],
        "ratio", colors=["green!45!black"], scale=1.5))
    write("r-order", bars(
        [("archive", [0.89]), ("probe order", [0.70]), ("reversed", [0.94])],
        "probes", colors=["orange!80!black"], scale=1.0))
    # four attempts on the sub-problem count, and the one that went round it
    # Three of the four COST time; a bar chart cannot draw a negative saving,
    # so they are drawn at zero and the caption says so. The point is the gap
    # between the two series, which is the whole finding.
    write("r-wall", bars(
        [("early exit", [25, 0]), ("contradiction", [24.8, 2]),
         ("range", [11.3, 0]), ("dominated", [15, 0])],
        "\\% removed / saved", scale=26))
    write("r-wall-legend", legend([("sub-problems removed", "blue!55!black"),
                                   ("time saved", "orange!80!black")]))
    # ---- the hybrid, on both illustration instances -----------------------
    for tag, build_inst, xlim, ylim, xt, yt in (
            ("ha", instance_a, (-4, 4), (-4, 10), [-4, -2, 0, 2, 4],
             [-4, -2, 0, 2, 4, 6, 8, 10]),
            ("hb", instance_b, (0, 13), (0, 7), [0, 4, 8, 12],
             [0, 2, 4, 6])):
        problem, phi, bounds = build_inst()
        feasible, efficient = enumerate_points(problem, bounds)
        found, steps = trace_seeding(problem, phi)
        write(f"{tag}-walk", hybrid_figure(problem, feasible, efficient, None,
                                           xlim, ylim, xt, yt,
                                           walk=found.points))
        for i, step in enumerate(steps, 1):
            write(f"{tag}-seed{i}",
                  hybrid_figure(problem, feasible, efficient, step,
                                xlim, ylim, xt, yt))
        front, popped = trace_after_seeding(problem, phi, found.points)
        write(f"{tag}-left",
              empty_boxes_figure(problem, feasible, efficient, popped,
                                 xlim, ylim, xt, yt))
        print(f"  {tag}: {len(steps)} seeding steps, "
              f"{len(popped)} boxes left to probe")
    write("h-process", process_diagram())
    print("figures written to", OUT)


if __name__ == "__main__":
    main()
